apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: angi-helloworld
  namespace: angi
spec:
  interval: 1m
  releaseName: angi-helloworld
  chart:
    git: https://github.com/dmyerscough/angi-helloworld
    ref: ec18199bc7e233a9c530f7fc1ca91fc4701a1b72
    path: sf-web-app/sf-web-app
  values:
    image:
      tag: 0.0.2