apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sf-web-app
  namespace: sf-web-app
spec:
  releaseName: sf-web-app
  chart:
    spec:
      chart: sf-web-app
      sourceRef:
        kind: HelmRepository
        name: sf-web-app
        namespace: sf-web-app
  interval: 1m
  install:
    remediation:
      retries: 3