apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sf-web-app
  namespace: skillfactory
spec:
  releaseName: sf-web-app
  chart:
    spec:
      chart: sf-web-app/sf-web-app
      sourceRef:
        kind: GitRepository
        name: sf-web-app
  interval: 50m
  install:
    remediation:
      retries: 3
  values:    
    service:
     type: NodePort
     port: 8000
     targetPort: 8000
     nodePort: 30091
     portName: metrics
    listenOnAllInterfaces: true
    db_name: 'django'
    db_username: 'admin'
    db_password: 'test123'
    db_host: 'my-release-postgresql.default.svc.cluster.local'
    db_port: '"5432"'