apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: angi-helloworld
  namespace: angi
spec:
  interval: 1m
  releaseName: angi-helloworld
  chart:
    git: https://github.com/dmyerscough/angi-helloworld
    path: sf-web-app/sf-web-app
  values:
    image:
      tag: 0.0.2