apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sf-web-app
  namespace: sf-web-app
spec:
  releaseName: sf-web-app
  chart:
    spec:
      chart: sf-web-app
      sourceRef:
        kind: HelmRepository
        name: sf-web-app
        namespace: sf-web-app
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    db_name: 'django'
    db_username: 'admin'
    db_password: 'test123'
    db_host: 'postgresql.postgresql.svc.cluster.local'
    db_port: "5432"
         