apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
spec:
  releaseName: prometheus-node-exporter
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-node-exporter
  interval: 50m
  install:
    remediation:
      retries: 3
  values:    
    service:
     type: NodePort
     port: 9100
     targetPort: 9100
     nodePort: 30091
     portName: metrics
    listenOnAllInterfaces: true
    annotations:
     prometheus.io/scrape: "true"