apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: angi-helloworld
  namespace: angi
spec:
  interval: 5m
  url: https://github.com/dmyerscough/angi-helloworld
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/