apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 1m
  url: https://morshimus.github.io/SkillFactory-Diploma-Work-Helm-Charts/