---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: '12.5.x'
      sourceRef:
        kind: OCIRepository
        name: postgresql
  interval: 50m
  install:
    remediation:
      retries: 3
  values: 
    auth:
      database: sf-web 
      username: admin
      password: test123
    metrics:
      enabled: true  
    persistence:
      size: 2Gi

