---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
  namespace: postgresql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: postgresql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 1m
  url: https://morshimus.github.io/SkillFactory-Diploma-Work-Helm-Charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: '12.5.x'
      sourceRef:
        kind: HelmRepository
        name: postgresql
  dependsOn:
    - name: infra-configs
      kind: Kustomization
      namespace: flux-system
      apiVersion: kustomize.toolkit.fluxcd.io/v1
  interval: 1m
  install:
    remediation:
      retries: 3
  values: 
    auth:
      database: 'django'
      username: 'admin'
    metrics:
      enabled: true  
    primary:
      persistence:
        existingClaim: postgresql-pvc
      

