---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    toolkit.fluxcd.io/tenant: sre-team

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 5m0s
  url: https://github.com/bitnami/charts
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: '12.5.x'
      sourceRef:
        kind: GitRepository
        name: postgresql
  interval: 5m
  install:
    remediation:
      retries: 3
#  values: 
#    auth:
#      database: sf-web 
#      username: admin
#      password: test123
#    metrics:
#      enabled: true  
#    persistence:
#      size: 2Gi

