apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - storageclass.yaml
  - persistentvolume.yaml
  - persistentvolumeclaims.yaml
  - repository.yaml
  - release.yaml