apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: '12.5.x'
      sourceRef:
        kind: HelmRepository
        name: postgresql
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    sealedsecret:
      enabled: true 
    auth:
      database: 'django'
      username: 'admin'
    metrics:
      enabled: true  
    primary:
      persistence:
        existingClaim: postgresql-pvc